# Railway deployment configuration for FastAPI backend

# Python runtime
runtime = "python-3.11"

# Build command
[build]
command = "pip install -r requirements.txt"

# Start command  
[deploy]
command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*'"

# Core environment variables needed (others optional)
[env]
DATABASE_URL = { required = true }
SECRET_KEY = { required = true }
FRONTEND_URL = { required = true }
DEBUG = { default = "false" }
ENVIRONMENT = { default = "production" }